### ISSUE TITLE
USB Webcam

### ISSUE THREAD

**Issue by jiffybutter** [jingw222/raspicam_vision_lite#1]
Hi,
I really like the idea of a webserver to view the output so I can run a headless Pi running Raspbian Lite. However, I only have a USB webcam, and I'm not sure how to implement the code for running this project with a USB webcam.

Also, what is the install process for opencv?

**Comment by jingw222** [comment]
Hi jiffybutter,

USB webcams can only be accessed by index via OpenCV's `VideoCapture` as in [camera.py](https://github.com/jingw222/raspicam_vision_lite/blob/master/app/camera.py). The Pi Camera Module works with `VideoStreamCV2` with index set to 0. Since I don't have a USB camera at hand, that's not been tested yet myself. But OpenCV does work with USB cameras for sure. Try experimenting with different values (make sure to switch your camera instance to `camera = VideoStreamCV2()` inside [\_\_init\_\_.py](https://github.com/jingw222/raspicam_vision_lite/blob/master/app/__init__.py)) to see which works for you. 

```
class VideoStreamCV2(object):
    def __init__(self, **kwargs):
        self.cap = cv2.VideoCapture(0, **kwargs)
...
```

As for installation for OpenCV, I followed these tutorials and found them pretty comprehensive and helpful ([pyimagesearch](https://www.pyimagesearch.com/2018/09/26/install-opencv-4-on-your-raspberry-pi/), [learnopencv](https://www.learnopencv.com/install-opencv-4-on-raspberry-pi/)). Certainly some configurations need to be adapted with your environment, so whenever you're not so sure about what a package does or what those flags mean when compiling, feel free to let me know, or just google it, cause that's exactly how I learn new things. :)
